pipeline {
    agent none
    stage('Docker') {
        docker {
            image 'docker'
        }
        steps {
            sh 'docker -v'
        }
    }
    stages {
        stage('Maven Install') {
            agent {
                docker {
                    image 'maven:3.9.5-eclipse-temurin-11'
                    args '-v /root/.m2:/root/.m2'
                    // Run the container on the node specified at the
                    // top-level of the Pipeline, in the same workspace,
                    // rather than on a new node entirely:
                    reuseNode true
                }
            }
            steps {
                sh 'mvn -B -v'
            }
        }
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
